## This should be places in the plugin directory
## for more help configuring see the wiki
## https://github.com/alkarinv/BattleArena/wiki
## Change this file to customize your event

CaptureTheFlag:
    enabled: true
    command: ctf
    matchTime: 300 # in seconds
    type: CaptureTheFlag
    database: ctf # or delete if you dont want wins/losses/top, needs BattleTracker
    prefix: "&8[CTF]&e"
    nTeams: 2
    teamSize: 1+
    victoryCondition: highestKills
    preReqs:
        options: [clearInventory]
    onJoin:
        options: [teleportWaitRoom, pvpOff, hunger=20]
    onOpen:
        options: [pvpOff]
    onPrestart:
        options: [pvpOff, deEnchant, woolTeams]
    onStart:
        options: [pvpOn, teleportIn, hunger=20]
    onDeath:
        options: [clearInventory, respawn]
    onComplete:
        options: [teleportOut, clearInventory, deEnchant, undisguise]
    onSpawn:
        options: [health=20, hunger=20]
        giveClass:
            default: gladiator
    winner:
        options: [health=20, hunger=20]