configVersion: 2.0

## This should be places in the plugin directory
## for more help configuring see the wiki
## https://github.com/alkarinv/BattleArena/wiki
## Change this file to customize your event

CaptureTheFlag:
    queue: true
    type: CaptureTheFlag
    prefix: "&8[CTF]&e"
    command: ctf
    database: ctf # or delete if you dont want wins/losses/top, needs BattleTracker
    matchTime: 300 # in seconds
    joinType: Queue
    victoryCondition: HighestKills
    nTeams: 2
    teamSize: 1+
    defaults: ## Global options for the entire match
        options: [woolTeams, alwaysTeamNames]
    preReqs:
        options: []
    onEnter:
        options: [storeAll]
    onLeave:
        options: [restoreAll]
    onJoin:
        options: [teleportWaitRoom, pvpOff, hunger=20]
    onOpen:
        options: [pvpOff]
    onPrestart:
        options: [pvpOff, deEnchant]
    onStart:
        options: [pvpOn, teleportIn, hunger=20]
    onDeath:
        options: [clearInventory, respawn]
    onComplete:
        options: [teleportOut]
    onSpawn:
        options: [health=20, hunger=20]
        giveClass:
            default: gladiator
    winner:
        options: [health=20, hunger=20]